


 export default [
   {
     catagoery: [
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/All.svg',
         name: 'All',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Resturants.svg',
         name: 'Restaurants',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Hotels.svg',
         name: 'Hotels',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Home.svg',
         name: 'Home services',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/shoping.svg',
         name: 'Shopping',
       },

       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/car location.svg',
         name: 'Car location',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Beauty.svg',
         name: 'Beauty & Spa',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Park.svg',
         name: 'Park',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/museam.svg',
         name: 'museum',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/car wash.svg',
         name: 'Car wash',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Bears.svg',
         name: 'Bars',
       },
       {
         id: crypto.randomUUID(),
         icon: '/image/Catageorys-icon/Gyms.svg',
         name: 'Gyms',
       },
     ],
     bestRating: [
       {
         id: crypto.randomUUID(),
         images: [
           '/image/BestRatingsImg/resturantsimg-1.svg',
           '/image/BestRatingsImg/resturantsimg-2.svg',
           '/image/BestRatingsImg/resturantsimg-3.svg',
           '/image/BestRatingsImg/resturantsimg-4.svg',
         ],
         name: 'Bottega',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: '/image/BestRatingsImg/rating-img.svg',
         ratingnum: '5.0',
         reviews: '(876 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/BestRatingsImg/resturantsimg-1.svg',
           '/image/BestRatingsImg/resturantsimg-2.svg',
           '/image/BestRatingsImg/resturantsimg-3.svg',
           '/image/BestRatingsImg/resturantsimg-4.svg',
         ],
         name: 'Bottega',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: '/image/BestRatingsImg/rating-img.svg',
         ratingnum: '5.0',
         reviews: '(876 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/BestRatingsImg/resturantsimg-1.svg',
           '/image/BestRatingsImg/resturantsimg-2.svg',
           '/image/BestRatingsImg/resturantsimg-3.svg',
           '/image/BestRatingsImg/resturantsimg-4.svg',
         ],
         name: 'Bottega',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: '/image/BestRatingsImg/rating-img.svg',
         ratingnum: '5.0',
         reviews: '(876 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/BestRatingsImg/resturantsimg-1.svg',
           '/image/BestRatingsImg/resturantsimg-2.svg',
           '/image/BestRatingsImg/resturantsimg-3.svg',
           '/image/BestRatingsImg/resturantsimg-4.svg',
         ],
         name: 'Bottega',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: '/image/BestRatingsImg/rating-img.svg',
         ratingnum: '5.0',
         reviews: '(876 reviews)',
       },
     ],
     latestTrands: [
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg1.png',
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg3.png',
           '/image/LatestTrands/trandsimg4.png',
         ],
         name: 'Bella Italy',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/notRating.svg',
         ],
         ratingnum: 4.3,
         reviews: '(34 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg3.png',
           '/image/LatestTrands/trandsimg4.png',
           '/image/LatestTrands/trandsimg5.png',
         ],
         name: 'Little Shucker',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
         ],
         ratingnum: 5.0,
         reviews: '(253 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg3.png',
           '/image/LatestTrands/trandsimg4.png',
           '/image/LatestTrands/trandsimg5.png',
         ],
         name: 'Marafuku Ramen',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/notRating.svg',
           '/image/LatestTrands/notRating.svg',
         ],
         ratingnum: 3.5,
         reviews: '(87 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg4.png',
           '/image/LatestTrands/trandsimg5.png',
           '/image/LatestTrands/trandsimg6.png',
           '/image/LatestTrands/trandsimg7.png',
         ],
         name: 'Buttega',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
         ],
         ratingnum: 5.0,
         reviews: '(876 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg5.png',
           '/image/LatestTrands/trandsimg6.png',
           '/image/LatestTrands/trandsimg7.png',
           '/image/LatestTrands/trandsimg8.png',
         ],
         name: 'Arabia Nights',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/half rating.svg',
           '/image/LatestTrands/notRating.svg',
         ],
         ratingnum: 3.5,
         reviews: '(334 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg6.png',
           '/image/LatestTrands/trandsimg7.png',
           '/image/LatestTrands/trandsimg8.png',
           '/image/LatestTrands/trandsimg9.png',
           '/image/LatestTrands/trandsimg10.png', 
           '/image/LatestTrands/trandsimg11.png', 
         ],
         name: 'Lokma',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
         ],
         ratingnum: 5.0,
         reviews: '(253 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg7.png',
           '/image/LatestTrands/trandsimg8.png',
         ],
         name: 'The snug',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/half rating.svg',
         ],
         ratingnum: 4.5,
         reviews: '(654 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg8.png',
           '/image/LatestTrands/trandsimg9.png',
           '/image/LatestTrands/trandsimg10.png', 
           '/image/LatestTrands/trandsimg11.png', 
         ],
         name: 'Starbelly',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
         ],
         ratingnum: 5.0,
         reviews: '(876 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg9.png',
           '/image/LatestTrands/trandsimg10.png', 
           '/image/LatestTrands/trandsimg11.png', 
           '/image/LatestTrands/trandsimg12.png', 
         ],
         name: 'Iori',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/half rating.svg',
           '/image/LatestTrands/notRating.svg',
         ],
         ratingnum: 3.5,
         reviews: '(334 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg10.png', 
           '/image/LatestTrands/trandsimg11.png', 
           '/image/LatestTrands/trandsimg12.png', 
           '/image/LatestTrands/trandsimg2.png',
         ],
         name: 'Ngalley',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/notRating.svg',
         ],
         ratingnum: 5.0,
         reviews: '(253 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg2.png',
         ],
         name: 'diogonal',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/LatestTrands/half rating.svg',
         ],
         ratingnum: 4.5,
         reviews: '(654 reviews)',
       },
       {
         id: crypto.randomUUID(),
         images: [
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg2.png',
           '/image/LatestTrands/trandsimg2.png',
         ],
         name: 'Kitoko',
         text: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout',
         ratingimg: [
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           '/image/BestRatingsImg/rating-img.svg',
           
         ],
         ratingnum: 5.0,
         reviews: '(876 reviews)',
       },
     ],
   },
 ];
